[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.build]
cmds = [
  "npm ci",
  "npx prisma generate",
  "npx prisma db push --skip-generate",
  "npm run build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public"
]

[start]
cmd = "node .next/standalone/server.js"
